typography_spectrum: 0.26873
color:
  brandColors:
    - '#141414'
    - '#c8c8c8'
    - '#8e8e8e'
    - '#a4a4a4'
    - '#444444'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.9548993967473507
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36011
analytics:
  google: null
  facebook: null
  twitter: null
name: BrandonSmith
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Testing the Headlines
description: What is this here
purpose: []
